refactor: 预移除trojan-go && 微调内存限制 && 升级proxy

diff --git a/config/proxy.yaml b/config/proxy.yaml
--- a/config/proxy.yaml
+++ b/config/proxy.yaml
@@ -23,51 +23,52 @@ spec:
       restartPolicy: Always
       terminationGracePeriodSeconds: 10
       volumes:
+        - name: sqlite-data
+          hostPath:
+            type: DirectoryOrCreate
+            path: /var/www/k8s/data/tmp/proxy
         - name: log
           persistentVolumeClaim:
             claimName: log
         - name: env
           configMap:
             name: proxy-env
-        - name: mysql
-          configMap:
-            name: trojan-go-cm
-      initContainers: #https://kubernetes.io/zh-cn/docs/concepts/workloads/pods/init-containers/
-        - name: wait-mysql #检测mysql存活,配置启动顺序
-          image: mysql:8.0-debian
-          imagePullPolicy: IfNotPresent
-          env:
-            - name: MYSQL_ROOT_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: mysql-secret
-                  key: root-pwd
-          command:
-            - sh
-            - -c
-            - |-
-              set -e
-              maxTries=15
-              while [ $maxTries -gt 0 ] && ! mysqladmin ping --connect-timeout=3 -s -hmysql-svc -uroot -p$MYSQL_ROOT_PASSWORD;do
-                  echo '等待mysql可用'
-                  sleep 1
-                  maxTries=$(( $maxTries - 1 ))
-              done
-              if [ $maxTries -le 0 ]; then
-                  echo >&2 'error: 尝试多次连接mysql服务失败'
-                  exit 1
-              fi
-              echo 'mysql已启动'
-          resources:
-            requests:
-              memory: 32Mi
-              cpu: 50m
-            limits:
-              memory: 512Mi
-              cpu: 1
+      # initContainers: #https://kubernetes.io/zh-cn/docs/concepts/workloads/pods/init-containers/
+      #   - name: wait-mysql #检测mysql存活,配置启动顺序
+      #     image: mysql:8.0-debian
+      #     imagePullPolicy: IfNotPresent
+      #     env:
+      #       - name: MYSQL_ROOT_PASSWORD
+      #         valueFrom:
+      #           secretKeyRef:
+      #             name: mysql-secret
+      #             key: root-pwd
+      #     command:
+      #       - sh
+      #       - -c
+      #       - |-
+      #         set -e
+      #         maxTries=15
+      #         while [ $maxTries -gt 0 ] && ! mysqladmin ping --connect-timeout=3 -s -hmysql-svc -uroot -p$MYSQL_ROOT_PASSWORD;do
+      #             echo '等待mysql可用'
+      #             sleep 1
+      #             maxTries=$(( $maxTries - 1 ))
+      #         done
+      #         if [ $maxTries -le 0 ]; then
+      #             echo >&2 'error: 尝试多次连接mysql服务失败'
+      #             exit 1
+      #         fi
+      #         echo 'mysql已启动'
+      #     resources:
+      #       requests:
+      #         memory: 32Mi
+      #         cpu: 50m
+      #       limits:
+      #         memory: 512Mi
+      #         cpu: 1
       containers:
         - name: proxy-container
-          image: ghcr.io/twbworld/proxy:1.2.4
+          image: ghcr.io/twbworld/proxy:1.3.0
           imagePullPolicy: IfNotPresent
           ports:
             - name: cp
@@ -84,10 +85,10 @@ spec:
                   apiVersion: v1
                   fieldPath: metadata.uid
           volumeMounts:
+            - name: sqlite-data
+              mountPath: /app/dao/
             - name: env
               mountPath: /volume/env/
-            - name: mysql
-              mountPath: /volume/mysql/
             - name: log
               mountPath: /app/log/
               subPathExpr: proxy-$(UUID)
@@ -96,7 +97,6 @@ spec:
             - -c
             - |
               ln -sf /volume/env/.env /app/config/.env #k8s单文件挂载内容不能同步,所以使用"挂载目录"+"软连接"解决
-              ln -sf /volume/mysql/config.json /app/config/.trojan-go
               ./server
           readinessProbe:
             initialDelaySeconds: 5
@@ -108,10 +108,10 @@ spec:
               path: /
           resources:
             requests:
-              memory: 32Mi
+              memory: 8Mi
               cpu: 50m
             limits:
-              memory: 256Mi
+              memory: 128Mi
               cpu: 500m
 
 ---
